- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- BB84.Notifications.sln
- Directory.Build.props
- dotnet-releaser.toml
changes:
- dotnet releaser added
- changelog added
- ci workflow added
- codeql workflow added
- build props fixed
closes #2
> feat: setup dotnet releaser

- src/BB84.Notifications/BB84.Notifications.csproj
- src/BB84.Notifications/BindableProperty.cs
- src/BB84.Notifications/Components/BindablePropertyChangedEventArgs.cs
- src/BB84.Notifications/Components/BindablePropertyChangingEventArgs.cs
- src/BB84.Notifications/Components/CollectionChangedEventArgs.cs
- src/BB84.Notifications/Components/CollectionChangingEventArgs.cs
- src/BB84.Notifications/Components/PropertyChangedEventArgs.cs
- src/BB84.Notifications/Components/PropertyChangingEventArgs.cs
- src/BB84.Notifications/Enumerators/CollectionEventType.cs
- src/BB84.Notifications/Interfaces/Components/INotifyCollectionChanged.cs
- src/BB84.Notifications/Interfaces/Components/INotifyCollectionChanging.cs
- src/BB84.Notifications/Interfaces/Components/INotifyPropertyChanged.cs
- src/BB84.Notifications/Interfaces/Components/INotifyPropertyChanging.cs
- src/BB84.Notifications/Interfaces/IBindableProperty.cs
- src/BB84.Notifications/Interfaces/INotifyCollectionBase.cs
- src/BB84.Notifications/Interfaces/INotifyPropertyBase.cs
- src/BB84.Notifications/NotifyCollectionBase.cs
- src/BB84.Notifications/NotifyPropertyBase.cs
changes:
- property changed components added
- property changing components added
- collection changed components added
- collection changing components added
- bindable property components added
- bases added
closes #5
> feat: add notification related things

- Directory.Build.props
changes:
- build props modified
closes #9
> feat: enable package validation

- Directory.Build.props
- src/BB84.Notifications/BindableProperty.cs
- src/BB84.Notifications/Components/CollectionChangedEventArgs.cs
- src/BB84.Notifications/Components/CollectionChangingEventArgs.cs
- src/BB84.Notifications/Enumerators/CollectionChangeAction.cs
- src/BB84.Notifications/NotifyCollectionBase.cs
- tests/BB84.NotificationsTests/BindablePropertyTests.Changed.cs
- tests/BB84.NotificationsTests/BindablePropertyTests.Changing.cs
- tests/BB84.NotificationsTests/BindablePropertyTests.cs
- tests/BB84.NotificationsTests/NotifyCollectionBaseTests.Changed.cs
- tests/BB84.NotificationsTests/NotifyCollectionBaseTests.Changing.cs
- tests/BB84.NotificationsTests/NotifyCollectionBaseTests.cs
- tests/BB84.NotificationsTests/NotifyPropertyBaseTests.Changed.cs
- tests/BB84.NotificationsTests/NotifyPropertyBaseTests.Changing.cs
- tests/BB84.NotificationsTests/NotifyPropertyBaseTests.cs
changes:
- unit tests added
- enumerator renamed
closes #6
> feat: add unit tests

- Directory.Build.props
- src/BB84.Notifications/BindableProperty.cs
- src/BB84.Notifications/Components/BindablePropertyChangedEventArgs.cs
- src/BB84.Notifications/Components/BindablePropertyChangingEventArgs.cs
- src/BB84.Notifications/Interfaces/IBindableProperty.cs
- src/BB84.Notifications/NotifyPropertyBase.cs
> fix: Bindable property and notify property do not work with enums

- Directory.Build.props
- README.md
changes:
- `README.md` modified
- version bump to `1.5.0`
closes #27
> docs: describe the attributes

- Directory.Build.props
- README.md
- src/BB84.Notifications/Components/PropertyChangedEventArgs.cs
- src/BB84.Notifications/Components/PropertyChangingEventArgs.cs
- src/BB84.Notifications/NotifyPropertyBase.cs
- tests/BB84.NotificationsTests/NotifyPropertyBaseTests.Changed.cs
- tests/BB84.NotificationsTests/NotifyPropertyBaseTests.Changing.cs
changes:
- added the `PropertyChangingEventArgs<T>`  class
- added the `PropertyChangedEventArgs<T>` class
- added unti tests
- changed the `NotifyPropertyBase` class
- changed the docs
closes #29
> feat: remove boxing unboxing

- Directory.Build.props
changes:
- updated `Directory.Build.props`
> chore: version bump to 1.6.1

- Directory.Build.props
- README.md
- src/BB84.Notifications/Components/CollectionChangedEventArgs.cs
- src/BB84.Notifications/Components/CollectionChangingEventArgs.cs
- src/BB84.Notifications/Interfaces/INotifyCollectionBase.cs
- src/BB84.Notifications/Interfaces/INotifyPropertyBase.cs
- src/BB84.Notifications/NotifyCollectionBase.cs
- src/BB84.Notifications/NotifyPropertyBase.cs
- tests/BB84.NotificationsTests/NotifyCollectionBaseTests.Add.cs
- tests/BB84.NotificationsTests/NotifyCollectionBaseTests.Move.cs
- tests/BB84.NotificationsTests/NotifyCollectionBaseTests.Remove.cs
- tests/BB84.NotificationsTests/NotifyCollectionBaseTests.Replace.cs
- tests/BB84.NotificationsTests/NotifyCollectionBaseTests.cs
changes:
- version bump to `1.7.0`
- modified the `README.md`
- modified the unit tests
- added `CollectionChangedEventArgs<T>` class
- added `CollectionChangingEventArgs<T>` class
- added `RaiseCollectionChanged<T>` method
- added `RaiseCollectionChanging<T>` method
closes #33
> feat: CollectionChangedEventArgs<T>

- src/BB84.Notifications/BindableProperty.cs
- src/BB84.Notifications/Interfaces/IBindableProperty.cs
- tests/BB84.NotificationsTests/BindablePropertyTests.IsDefault.cs
changes:
- `IBindableProperty` modified
- `BindableProperty` modified
- unit tests added
closes https://github.com/BoBoBaSs84/BB84.Notifications/issues/48
> feat: add IsDefault to bindable property

- src/BB84.Notifications/Attributes/NotifyChangedAttribute.cs
- src/BB84.Notifications/Attributes/NotifyChangingAttribute.cs
- src/BB84.Notifications/BindableProperty.cs
- src/BB84.Notifications/Components/CollectionChangedEventArgs.cs
- src/BB84.Notifications/Components/CollectionChangingEventArgs.cs
- src/BB84.Notifications/Components/PropertyChangedEventArgs.cs
- src/BB84.Notifications/Components/PropertyChangingEventArgs.cs
changes:
- some constructors modified
closes #46
> refactor: use primary constructor

- src/BB84.Notifications/Interfaces/IRelayCommand.cs
- src/BB84.Notifications/RelayCommand.cs
- tests/BB84.NotificationsTests/RelayCommandTests.CanExecute.cs
- tests/BB84.NotificationsTests/RelayCommandTests.Execute.cs
- tests/BB84.NotificationsTests/RelayCommandTests.NotifyCanExecuteChanged.cs
- tests/BB84.NotificationsTests/RelayCommandTests.cs
changes:
- the `IRelayCommand` interface added
- the `RelayCommand` class added
- unit tests added
closes #55
> feat: relay command implementation

- src/BB84.Notifications/BB84.Notifications.csproj
- src/BB84.Notifications/Interfaces/IValidatableObject.cs
- src/BB84.Notifications/ValidatableObject.cs
- tests/BB84.NotificationsTests/RelayCommandTests.NotifyCanExecuteChanged.cs
- tests/BB84.NotificationsTests/ValidatableObjectTests.Errors.cs
- tests/BB84.NotificationsTests/ValidatableObjectTests.ErrorsChanged.cs
- tests/BB84.NotificationsTests/ValidatableObjectTests.NoErrors.cs
- tests/BB84.NotificationsTests/ValidatableObjectTests.cs
changes:
- added `IValidatableObject` interface
- added `ValidatableObject` class
- unit tests added
- small fixes applied
> feat: validatable object

- src/BB84.Notifications/RelayCommand.cs
- tests/BB84.NotificationsTests/Attributes/NotifyChangedAttributeTests.cs
- tests/BB84.NotificationsTests/Attributes/NotifyChangingAttributeTests.cs
- tests/BB84.NotificationsTests/BindablePropertyTests.cs
- tests/BB84.NotificationsTests/NotificationCollectionTests.cs
- tests/BB84.NotificationsTests/RelayCommandTests.cs
changes:
- changed `Action<object?>` to `Action`
- changed `Predicate<object?>?` to `Func<bool>?`
- small refactoring
closes #63
> refactor: relay command review

- Directory.Build.props
changes:
- bumped version to `3.3.x`
> chore: version bump

- src/BB84.Notifications/Interfaces/IValidatableObject.cs
- src/BB84.Notifications/ValidatableObject.cs
- tests/BB84.NotificationsTests/ValidatableObjectTests.Validate.cs
- tests/BB84.NotificationsTests/ValidatableObjectTests.cs
changes:
- added new `IsValid` property
- added new `Validate` method
- changed the `RaiseErrorsChanged` method from `private` to `protected
- changed the `Vaildate<T>` method from `private` to `protected
closes #112
> feat: validatable object add validate method

- src/BB84.Notifications/NotifiableObject.cs
- tests/BB84.NotificationsTests/Attributes/NotifyChangedAttributeTests.cs
- tests/BB84.NotificationsTests/Attributes/NotifyChangingAttributeTests.cs
changes:
- modified the `NotifiableObject` class
- fixed the `NotifyChangedAttributeTests` class
- fixed the `NotifyChangingAttributeTests` class
closes #114
> feat: improve performance through caching

- Directory.Build.props
changes:
- modifed the `Directory.Build.props` file
closes #116
> chore: bump version and make a new release

- src/BB84.Notifications/NotifiableObject.cs
changes:
- changed the bakcing fileds to non static
closes #118
> fix: static backing field leads to error

- src/BB84.Notifications/Interfaces/IReversibleProperty.cs
- src/BB84.Notifications/ReversibleProperty.cs
- tests/BB84.NotificationsTests/ReversiblePropertyTests.NextValue.cs
- tests/BB84.NotificationsTests/ReversiblePropertyTests.PreviousValue.cs
- tests/BB84.NotificationsTests/ReversiblePropertyTests.SetProperty.cs
- tests/BB84.NotificationsTests/ReversiblePropertyTests.cs
**changes:**
- [feat: reversible property interface and implementation added](https://github.com/BoBoBaSs84/BB84.Notifications/commit/1ed1c60f5b8aa9d52b2bacf4b343530f977045ab)
- [fix: comments fixed](https://github.com/BoBoBaSs84/BB84.Notifications/commit/0245eb717120deecebb937f4bacf6f030f5e545a)
- [feat: unit tests added](https://github.com/BoBoBaSs84/BB84.Notifications/commit/cbcb6c98ca402bace05d25b62801b18e3e667785)
closes #130
> feat: reversible property

- Directory.Build.props
- README.md
changes:
- [docs: reversible property](https://github.com/BoBoBaSs84/BB84.Notifications/commit/ba9e211bdd0036559c7565021ee3289996a34eef)
- [chore: version bump to 3.5.x](https://github.com/BoBoBaSs84/BB84.Notifications/commit/431316c273d9a7f20b36da5d38d032dac28d538a)
closes #132
> docs: reversible property

- .github/workflows/ci.yml
- src/BB84.Notifications/NotifiableObject.cs
- tests/BB84.NotificationsTests/NotifiablePropertyTests.IsDefault.cs
- tests/BB84.NotificationsTests/NotifiablePropertyTests.IsNull.cs
- tests/BB84.NotificationsTests/NotifiablePropertyTests.cs
- tests/BB84.NotificationsTests/ReversiblePropertyTests.cs
> feat: do some refactoring

- README.md
**changes:**
- [chore(docs): improved the readme file](https://github.com/BoBoBaSs84/BB84.Notifications/commit/e0d0336d637310f820f8afe95a9bd9972660a010)
closes #162
> chore(docs): improved the readme file
